name       : winff
version    : 1.5.5
release    : 1
source     :
    - http://winff.org/docs/source/winff-1.5.5-source.tar.gz : 3f67400ab8f7f43d2290dff3c5a0a8b8a966ba67cd971edb5d63e6a127d7a485
license    : GPL-3.0
component  : multimedia.video
summary    : graphical video and audio batch converter using ffmpeg or avconv
description: |
    graphical video and audio batch converter using ffmpeg or avconv
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - lazarus
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus winff.lpr
install    : |-
    install -D -m 00755 winff $installdir/usr/bin/winff
    install -D -m 00644 winff.1 $installdir/usr/share/man/man1/winff.1
    install -D -m 00644 presets.xml $installdir/usr/share/winff/presets.xml
    for lang in `ls -1 languages/*.po`; do
        install -D -m 00644 $lang $installdir/usr/share/winff/$lang
    done
    for size in 16x16 24x24 32x32 48x48; do
        install -D -m 00644 winff-icons/$size/winff.png $installdir/usr/share/icons/hicolor/$size/apps/winff.png
    done
    install -D -m 00644 $pkgfiles/winff.desktop $installdir/usr/share/applications/winff.desktop
